EMOTION_RULES = {
    "negative": {
        "sad": -2,
        "depressed": -2.5,
        "down": -1.5,
        "anxious": -2,
        "stressed": -2,
        "overwhelmed": -2.5,
        "lonely": -2,
        "frustrated": -1.5,
        "tired of": -2,
        # 한국어 STT 감정 표현 반영.
        "슬퍼": -2,
        "슬프": -2,
        "우울": -2.5,
        "기분이 안": -1.5,
        "마음이 안": -1.5,
        "불안": -2,
        "걱정": -1.5,
        "스트레스": -2,
        "외로": -2,
        "쓸쓸": -1.5,
        "서운": -1.5,
        "답답": -1.5,
        "짜증": -1.5,
        "화가": -1.5,
        "죽고 싶": -4,
        "살기 싫": -4,
        "그만 살": -4,
    },
    "positive": {
        "happy": +2,
        "good": +1,
        "great": +2,
        "relaxed": +1.5,
        "calm": +1.5,
        "better": +1.5,
        "excited": +2,
        # 회복/긍정 신호 반영.
        "행복": +2,
        "좋아": +1,
        "좋다": +1,
        "괜찮": +1,
        "편안": +1.5,
        "차분": +1.5,
        "나아졌": +1.5,
        "신나": +2,
        "기쁘": +2,
        "고마": +1,
    },
}

ENERGY_RULES = {
    "negative": {
        "tired": -2,
        "exhausted": -2.5,
        "fatigued": -2,
        "sleepy": -1.5,
        "no energy": -2.5,
        "pain": -2,
        "headache": -1.5,
        "back pain": -1.5,
        "burned out": -2.5,
        # 피로/통증 구어체 반영.
        "피곤": -2,
        "지쳤": -2,
        "지치": -2,
        "기운이 없": -2.5,
        "힘이 없": -2.5,
        "힘들": -2,
        "졸려": -1.5,
        "잠이 와": -1.5,
        "아파": -2,
        "아프": -2,
        "두통": -1.5,
        "허리": -1.5,
        "무릎": -1.5,
        "삭신": -1.5,
        "몸살": -2,
    },
    "positive": {
        "energetic": +2,
        "active": +1.5,
        "worked out": +2,
        "went for a walk": +1.5,
        "feeling strong": +1.5,
        # 활동/회복 표현 반영.
        "기운 나": +2,
        "활기": +1.5,
        "운동": +2,
        "산책": +1.5,
        "걸었": +1.5,
        "걸었다": +1.5,
        "힘이 나": +1.5,
    },
}

PHRASE_RULES = [
    ("not myself", -2),
    ("feeling off", -1.5),
    ("getting worse", -2),
    ("getting better", +1.5),
    ("i'm fine", +0.5),
    # 문장 단위 컨디션 표현 반영.
    ("내가 내가 아닌 것 같", -2),
    ("몸이 이상", -1.5),
    ("컨디션이 안", -1.5),
    ("점점 나빠", -2),
    ("더 안 좋아", -2),
    ("좀 나아", +1.5),
    ("괜찮아졌", +1.5),
]

HEALTH_KEYWORD_RULES = {
    # 건강 위험 후보 표현 우선.
    "chest pain",
    "short of breath",
    "hard to breathe",
    "dizzy",
    "fainted",
    "fell down",
    "blood pressure",
    "diabetes",
    "fever",
    "vomit",
    "diarrhea",
    "hospital",
    "medicine",
    "가슴 통증",
    "가슴이 아",
    "숨이 차",
    "숨쉬기",
    "호흡",
    "어지러",
    "쓰러졌",
    "기절",
    "넘어졌",
    "낙상",
    "혈압",
    "당뇨",
    "열이 나",
    "고열",
    "구토",
    "토했",
    "설사",
    "피가",
    "출혈",
    "병원",
    "응급",
    "119",
    "약을",
    "약 먹",
}

HEALTH_CONTEXT_SUPPRESS_RULES = {
    # 실제 위급이 아닌 맥락 제외.
    "아프지 않",
    "아픈 건 아니",
    "통증은 없",
    "숨이 차지 않",
    "괜찮아졌",
    "괜찮아요",
    "괜찮다",
    "나아졌",
    "다녀왔",
    "진료받",
    "약 먹었",
    "뉴스에서",
    "드라마에서",
    "친구가",
    "이웃이",
    "남편이",
    "아내가",
    "자식이",
    "not in pain",
    "no pain",
    "not dizzy",
    "not short of breath",
    "already went",
    "saw a doctor",
    "took medicine",
}
